name: C/C++ CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup C/C++ Compiler
      uses: rlalik/setup-cpp-compiler@v1.1
      with:
        compiler: gcc 6.3
    - name: Change wrapper permissions
      run: chmod +x ./hello.c
    - name: configure
      run: ./hello.c
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: make distcheck
      run: echo Workflow executed successfully
